# main
services:
- type: web
  name: kiss-rerank
  runtime: python
  repo: https://github.com/soderalohastrom/kiss-rerank
  branch: query
  plan: standard
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
  envVars:
    - key: PYTHONUNBUFFERED
      value: "1"
    - key: LOG_LEVEL
      value: "INFO"
version: "1"
